# Generated by Django 5.1.3 on 2024-11-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='no_of_items',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
